'use strict';
(()=>{
const D=window.ORB_DATA,points=D.points,byId=Object.fromEntries(points.map(p=>[p.id,p])),q=s=>document.querySelector(s),audio=q('#audio');
let imageMode="photo";
let current=byId[decodeURIComponent(location.hash.slice(1))]||points[0],courseMode=false,trail=[],saved=null,rotation=0,targetRotation=null,auto=!matchMedia('(prefers-reduced-motion: reduce)').matches,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=s=>{q('#notice').textContent=s;clearTimeout(msg.timer);msg.timer=setTimeout(()=>q('#notice').textContent='',4500)};
try{saved=JSON.parse(localStorage.getItem(D.id+'-learn'));if(saved?.revision!==D.course.scriptRevision)saved=null}catch{}
function remember(){if(!Number.isFinite(audio.currentTime))return;saved={time:audio.currentTime,revision:D.course.scriptRevision};try{localStorage.setItem(D.id+'-learn',JSON.stringify(saved))}catch{}updateResume()}
function updateResume(){q('#resume').disabled=!saved||saved.time<1;q('#resume').textContent=saved&&saved.time>=1?'Resume · '+fmt(saved.time):'Resume your spiral'}
function selectedAt(t){return [...points].reverse().find(p=>t>=p.start)||points[0]}
function choose(id,{guided=false,focus=false}={}){const p=byId[id];if(!p)return;if(!guided){audio.pause();courseMode=false}current=p;history.replaceState(null,'','#'+p.id);document.title=p.title+' · South Sound Salmon ORB';if(trail.at(-1)!==p.id)trail.push(p.id);trail=trail.slice(-8);render();q('#navigation-note').textContent='Arrow keys: broaden, deepen, or turn the orb. Page Up / Down: journey.';if(focus)q('#reading').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'});targetRotation=-coords(p).lon;}
function render(){const p=current;q('#point-title').textContent=p.title;q('#kind').textContent=p.kind==='floor'?'KNOWLEDGE FLOOR · LOCAL EVIDENCE GAP':p.kind.toUpperCase();q('#count').textContent=`${p.order+1} / ${points.length}`;renderImage();q('#reading-mode').textContent=courseMode?'ORB Learn · matching narration transcript':'Explore · field notes';q('#prose').innerHTML=(courseMode?p.paragraphs:p.reading).map((t,i)=>`<p data-paragraph="${i}">${escape(t)}</p>`).join('');q('#visit-details').innerHTML=p.kind==='location'?`${p.event?'<p class="event">'+escape(p.event)+'</p>':''}<dl><dt>Visit</dt><dd>${escape(p.dates)} · 2026</dd><dt>Drive</dt><dd>${escape(p.drive)} from Olympia, approximate</dd><dt>Timing</dt><dd>${escape(p.time)}</dd><dt>Access</dt><dd>${escape(p.access)} <a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.mapQuery)}">Open map ↗</a></dd><dt>Evidence</dt><dd>${escape(p.certainty)}</dd></dl>`:'';q('#sources').innerHTML=p.sources.map(id=>`<li><a href="${escape(D.sources[id].url)}" target="_blank" rel="noopener">${escape(D.sources[id].title)}</a></li>`).join('');q('#trail').textContent='Visited: '+trail.map(id=>byId[id].label).join(' → ');document.querySelectorAll('[data-point]').forEach(el=>{el.classList.toggle('active',el.dataset.point===p.id);el.setAttribute('aria-current',el.dataset.point===p.id?'true':'false')});for(const dir of ['up','down','forward','backward']){const button=q(`[data-dir="${dir}"]`),id=destination(dir);button.disabled=!id;button.title=id?byId[id].title:edgeReason(dir)}q('#browse').hidden=!courseMode;}
function renderImage(){const p=current,photo=imageMode==='photo'&&p.photo,im=q('#point-image');im.src=photo?photo.image:p.image;im.alt=photo?photo.alt:p.alt;im.dataset.type=photo?'photo':'illustration';q('#caption').textContent=photo?photo.caption:p.caption;q('#photo-credit').innerHTML=photo?`Photo: ${escape(photo.creator)} · <a href="${escape(photo.sourceUrl)}" target="_blank" rel="noopener">Original &amp; date</a> · <a href="${escape(photo.licenseUrl)}" target="_blank" rel="noopener">${escape(photo.license)}</a> <span class="photo-changes">Resized; no generative editing.</span>`:'';q('#photo-mode').setAttribute('aria-pressed',!!photo);q('#illustration-mode').setAttribute('aria-pressed',!photo);q('#photo-mode').disabled=!p.photo;}
q('#photo-mode').onclick=()=>{imageMode='photo';renderImage()};q('#illustration-mode').onclick=()=>{imageMode='illustration';renderImage()};
function destination(dir){if(dir==='up')return current.parent;if(dir==='down')return current.children[0];if(dir==='forward'||dir==='backward')return current.thread[dir];const sibs=points.filter(p=>p.parent===current.parent);if(sibs.length<2)return null;const i=sibs.indexOf(current);return sibs[(i+(dir==='left'?-1:1)+sibs.length)%sibs.length].id}
function edgeReason(dir){return dir==='up'?'This is the guide’s broadest authored point.':dir==='down'?(current.edgeReason||'No finer point is authored on this branch. Use the sources or continue in Orbiverse.'):'This is the '+(dir==='forward'?'end':'beginning')+' of the educational journey.'}
function move(dir){const id=destination(dir);if(id)choose(id);else if(dir==='left'||dir==='right'){targetRotation=null;rotation+=(dir==='left'?-.55:.55)}else msg(edgeReason(dir));q('#navigation-note').textContent=id?`${dir.toUpperCase()} → ${byId[id].title}`:edgeReason(dir)}
async function playAt(time){if(!D.course.audioReady){msg('The recording is not available.');return}courseMode=true;audio.currentTime=Math.min(time,D.course.duration-.01);q('#transport').hidden=false;choose(selectedAt(audio.currentTime).id,{guided:true});try{await audio.play()}catch{msg('Playback could not start. Press Play to try again.')}updatePlayback()}
function updatePlayback(){q('#play').textContent=audio.paused?'▶':'Ⅱ';q('#play').setAttribute('aria-label',audio.paused?'Play course':'Pause course');q('#now-title').textContent=courseMode?current.label:'Course paused · '+selectedAt(audio.currentTime).label;q('#clock').textContent=fmt(audio.currentTime)+' / '+fmt(D.course.duration||0);q('#seek').value=audio.currentTime;}
q('#start').onclick=()=>{playAt(0);q('#explore').scrollIntoView({behavior:reduce?'auto':'smooth'})};q('#learn-top').onclick=()=>q('#start').click();q('#resume').onclick=()=>playAt(saved?.time||0);q('#listen').onclick=()=>playAt(current.start||0);q('#browse').onclick=()=>choose(current.id);q('#play').onclick=()=>audio.paused?playAt(audio.currentTime):audio.pause();q('#close-player').onclick=()=>{audio.pause();q('#transport').hidden=true};q('#seek').oninput=e=>{courseMode=true;audio.currentTime=+e.target.value;choose(selectedAt(audio.currentTime).id,{guided:true});updatePlayback();remember()};q('#speed').onchange=e=>audio.playbackRate=+e.target.value;
audio.addEventListener('timeupdate',()=>{if(courseMode){const p=selectedAt(audio.currentTime);if(p.id!==current.id)choose(p.id,{guided:true});q('#prose').querySelectorAll('p').forEach((el,i)=>el.classList.toggle('spoken',(current.cues||[]).some(c=>c.paragraph===i&&audio.currentTime>=c.start&&audio.currentTime<c.end)))}updatePlayback();remember()});audio.addEventListener('play',updatePlayback);audio.addEventListener('pause',()=>{updatePlayback();remember()});audio.addEventListener('ended',()=>{q('#now-title').textContent='Journey complete · explore a river or start again';msg('Your spiral is complete. Choose a place to explore.');saved=null;try{localStorage.removeItem(D.id+'-learn')}catch{}updateResume()});audio.addEventListener('error',()=>msg('Audio could not load. The complete script remains available below Sources.'));
q('#print').onclick=()=>{q('#evidence').open=true;window.print()};q('#continue').onclick=()=>{const p=current;q('#continuation-text').value=`Continue /orbiverse from South Sound Salmon Watching Guide, point “${p.title}” (${p.id}).\nEdition: autumn 2026; sources checked September 8, 2026.\n${p.reading.join('\n\n')}\nSources: ${p.sources.map(s=>D.sources[s].url).join(', ')}\nVisited: ${trail.join(' → ')}\nBroaden to related watersheds or deepen the evidence. Recheck current dates and access; never treat generated illustrations as field observations. ${p.question?'Knowledge floor: '+p.question:''}`;q('#continuation').showModal()};q('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(q('#continuation-text').value);q('#copy-status').textContent='Copied. Paste into your AI conversation.'}catch{q('#continuation-text').select();q('#copy-status').textContent='Select and copy the text above.'}};
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(b.dataset.dir));document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||q('#continuation').open||e.altKey||e.ctrlKey||e.metaKey)return;const dir={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',PageDown:'forward',PageUp:'backward'}[e.key];if(dir){e.preventDefault();move(dir)}});window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(byId[id])choose(id)});
const labels=q('#point-labels');for(const p of points){const b=document.createElement('button');b.textContent=p.label;b.className='point-label';b.dataset.point=p.id;b.title=p.title;b.onclick=()=>choose(p.id);labels.append(b);const row=b.cloneNode(true);row.className='';row.onclick=()=>choose(p.id,{focus:true});q('#point-index').append(row)}
function renderLocations(month='all'){q('#locations').innerHTML=points.filter(p=>p.kind==='location'&&(month==='all'||+p.dateStart.slice(5,7)<=+month&&+p.dateEnd.slice(5,7)>=+month)).sort((a,b)=>a.dateStart.localeCompare(b.dateStart)).map(p=>`<tr><td><button data-location="${p.id}">${escape(p.label)}</button><small>${escape(p.region)}</small></td><td>${escape(p.dates)}${p.event?'<small>Confirmed opening / event in field notes</small>':''}</td><td>${escape(p.drive)}</td><td>${escape(p.species)}</td></tr>`).join('');q('#locations').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.location,{focus:true}));}document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-month]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderLocations(b.dataset.month)});
const canvas=q('#sphere'),ctx=canvas.getContext('2d');let size=400,last=performance.now();function coords(p){return{lon:p.order/(points.length-1)*Math.PI*5,lat:-1.1+p.order/(points.length-1)*2.2}}
function project(lon,lat){const c=Math.cos(lat),x=Math.sin(lon+rotation)*c,y=Math.sin(lat),z=Math.cos(lon+rotation)*c;return{x:size/2+x*size*.36,y:size/2+y*size*.39,z}}
function path(values,color,width=1){ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function resize(){size=q('#orb').clientWidth;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=size*dpr;canvas.height=size*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}new ResizeObserver(resize).observe(q('#orb'));resize();
function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;if(!reduce){if(targetRotation!==null){let delta=Math.atan2(Math.sin(targetRotation-rotation),Math.cos(targetRotation-rotation));rotation+=delta*Math.min(1,dt*3);if(Math.abs(delta)<.01)targetRotation=null}else if(auto&&!q('#orb').dataset.hover)rotation+=dt*.045}else if(targetRotation!==null){rotation=targetRotation;targetRotation=null}ctx.clearRect(0,0,size,size);const grad=ctx.createRadialGradient(size*.45,size*.42,0,size/2,size/2,size*.46);grad.addColorStop(0,'#204f3c55');grad.addColorStop(1,'#10282300');ctx.fillStyle=grad;ctx.fillRect(0,0,size,size);ctx.beginPath();ctx.ellipse(size/2,size/2,size*.36,size*.39,0,0,Math.PI*2);ctx.strokeStyle='#55705b55';ctx.stroke();for(let lat=-.8;lat<=.8;lat+=.4)path(Array.from({length:101},(_,i)=>project(i/100*Math.PI*2,lat)),'#63806824');for(let lon=0;lon<Math.PI;lon+=Math.PI/4)path(Array.from({length:101},(_,i)=>project(lon,-Math.PI/2+i/100*Math.PI)),'#63806822');const spiral=Array.from({length:241},(_,i)=>{const u=i/240;return project(u*Math.PI*5,-1.1+u*2.2)});path(spiral,'#d5ad6648',1.3);if(courseMode){const progress=audio.currentTime/(D.course.duration||1);path(spiral.slice(0,Math.max(2,Math.floor(progress*240))),'#e7b86bb0',2)}const placed=[];points.forEach((p,i)=>{const c=coords(p),v=project(c.lon,c.lat),b=labels.children[i];b.hidden=v.z<-.05&&p.id!==current.id;let ly=v.y;if(!b.hidden){const w=Math.min(160,p.label.length*6.8+12);for(const old of placed){if(Math.abs(v.x-old.x)<(w+old.w)/2+3&&ly-old.y<18)ly=old.y+18;}placed.push({x:v.x,y:ly,w});}b.style.left=v.x+'px';b.style.top=ly+'px';b.style.opacity=p.id===current.id?'1':String(.33+(v.z+1)*.31);b.style.zIndex=String(Math.round((v.z+1)*10));b.style.fontSize=(size<400?11:12)+(v.z+1)*.8+'px';ctx.beginPath();ctx.arc(v.x,v.y+11,p.id===current.id?3:1.5,0,Math.PI*2);ctx.fillStyle=p.id===current.id?'#f0c47a':'#a9c4ab80';ctx.fill()});requestAnimationFrame(frame)}
q('#motion').onclick=()=>{auto=!auto;targetRotation=null;q('#motion').textContent=auto?'Pause rotation':'Rotate orb';q('#motion').setAttribute('aria-pressed',!auto)};q('#motion').textContent=auto?'Pause rotation':'Rotate orb';q('#motion').setAttribute('aria-pressed',!auto);q('#orb').addEventListener('pointerenter',()=>{q('#orb').dataset.hover='true'});q('#orb').addEventListener('pointerleave',()=>{delete q('#orb').dataset.hover});
q('#course-meta').textContent=D.course.audioReady?`${fmt(D.course.duration)} recorded · Michael · 20 stops`:'Text course available; recording pending';q('#seek').max=D.course.duration||100;renderLocations();choose(current.id);updateResume();requestAnimationFrame(frame);
})();
